/**
 * Stellar structure, evolution and populations.
 *
 * Stars are generated by sampling a Kroupa initial mass function, then every
 * other property - luminosity, radius, temperature, lifetime, colour, and what
 * the star has already turned into given the age of its galaxy - follows from
 * that one mass through standard main-sequence relations. Nothing is hand-tuned.
 */

import { L_SUN, M_SUN, R_SUN, SIGMA_SB, T_SUN, AU } from '../core/constants';
import { RNG } from '../core/rng';
import { blackbodyRGB } from './blackbody';

export type StellarClass = 'O' | 'B' | 'A' | 'F' | 'G' | 'K' | 'M' | 'L' | 'T';
export type StellarKind =
  | 'main-sequence' | 'subgiant' | 'giant' | 'supergiant'
  | 'white-dwarf' | 'neutron-star' | 'black-hole' | 'brown-dwarf';

export interface Star {
  /** Zero-age main-sequence mass, in solar masses. */
  massMsun: number;
  /** Current mass (mass loss matters for remnants), solar masses. */
  currentMassMsun: number;
  /** Bolometric luminosity, solar units. */
  luminosityLsun: number;
  /** Radius, solar radii. */
  radiusRsun: number;
  /** Effective temperature, K. */
  teff: number;
  /** Age, Gyr. */
  ageGyr: number;
  /** Main-sequence lifetime, Gyr. */
  lifetimeGyr: number;
  /** Metallicity [Fe/H], dex relative to solar. */
  metallicity: number;
  kind: StellarKind;
  spectralClass: StellarClass;
  /** Sub-class digit 0-9 (e.g. G2). */
  subClass: number;
  /** Luminosity class in Roman numerals. */
  luminosityClass: string;
  /** Linear-light RGB from the blackbody spectrum. */
  color: [number, number, number];
  /** Inner and outer conservative habitable-zone radii, AU. */
  habitableZoneAu: [number, number];
}

/**
 * Kroupa (2001) broken-power-law IMF:
 *   dN/dm ∝ m^-1.3   for 0.08 - 0.5 Msun
 *   dN/dm ∝ m^-2.3   for      > 0.5 Msun
 * Sampled by inverse CDF across the two segments.
 */
export function sampleKroupaIMF(rng: RNG, mMin = 0.08, mMax = 120): number {
  const a1 = -1.3, a2 = -2.3, mBreak = 0.5;
  const seg1 = mMin < mBreak;
  const hi1 = Math.min(mBreak, mMax);
  const int = (lo: number, hi: number, al: number, norm: number) =>
    norm * (Math.pow(hi, al + 1) - Math.pow(lo, al + 1)) / (al + 1);
  // Continuity of the density at the break
  const norm2 = Math.pow(mBreak, a1 - a2);
  const I1 = seg1 ? int(mMin, hi1, a1, 1) : 0;
  const I2 = mMax > mBreak ? int(Math.max(mBreak, mMin), mMax, a2, norm2) : 0;
  const u = rng.next() * (I1 + I2);
  if (u < I1) {
    const t = (u * (a1 + 1)) / 1 + Math.pow(mMin, a1 + 1);
    return Math.pow(t, 1 / (a1 + 1));
  }
  const lo = Math.max(mBreak, mMin);
  const t = ((u - I1) * (a2 + 1)) / norm2 + Math.pow(lo, a2 + 1);
  return Math.pow(t, 1 / (a2 + 1));
}

/**
 * Main-sequence mass-luminosity relation, piecewise power law
 * (Salaris & Cassisi 2005 / Duric 2004 breakpoints).
 */
export function msLuminosity(m: number): number {
  if (m < 0.43) return 0.23 * Math.pow(m, 2.3);
  if (m < 2) return Math.pow(m, 4);
  if (m < 55) return 1.4 * Math.pow(m, 3.5);
  return 32000 * m; // radiation-pressure dominated, near Eddington
}

/** Main-sequence mass-radius relation. */
export function msRadius(m: number): number {
  if (m < 1) return Math.pow(m, 0.8);
  return Math.pow(m, 0.57);
}

/** Effective temperature from L and R via Stefan-Boltzmann. */
export function teffFrom(Lsun: number, Rsun: number): number {
  const L = Lsun * L_SUN;
  const R = Rsun * R_SUN;
  return Math.pow(L / (4 * Math.PI * R * R * SIGMA_SB), 0.25);
}

/** Main-sequence lifetime in Gyr: 10 Gyr * (M/L) in solar units. */
export const msLifetimeGyr = (m: number): number => (10 * m) / msLuminosity(m);

export function spectralClassOf(teff: number): [StellarClass, number] {
  const table: [StellarClass, number, number][] = [
    ['O', 30000, 60000], ['B', 10000, 30000], ['A', 7500, 10000], ['F', 6000, 7500],
    ['G', 5200, 6000], ['K', 3700, 5200], ['M', 2400, 3700], ['L', 1300, 2400], ['T', 500, 1300],
  ];
  for (const [cls, lo, hi] of table) {
    if (teff >= lo && teff < hi) {
      const frac = (hi - teff) / (hi - lo);
      return [cls, Math.max(0, Math.min(9, Math.floor(frac * 10)))];
    }
  }
  return teff >= 60000 ? ['O', 0] : ['T', 9];
}

/**
 * Conservative habitable zone, Kopparapu et al. (2013) "runaway greenhouse" to
 * "maximum greenhouse" limits, with the Teff-dependent correction.
 */
export function habitableZone(Lsun: number, teff: number): [number, number] {
  const ts = teff - T_SUN;
  const lim = (s0: number, a: number, b: number, c: number, d: number) =>
    s0 + a * ts + b * ts * ts + c * ts * ts * ts + d * ts * ts * ts * ts;
  const sInner = lim(1.0512, 1.3242e-4, 1.5418e-8, -7.9895e-12, -1.8328e-15);
  const sOuter = lim(0.3438, 5.8942e-5, 1.6558e-9, -3.0045e-12, -5.2983e-16);
  return [Math.sqrt(Lsun / sInner), Math.sqrt(Lsun / sOuter)];
}

/** Remnant mass after stellar death, solar masses (initial-final mass relation). */
export function remnantMass(m: number): { mass: number; kind: StellarKind } {
  if (m < 0.08) return { mass: m, kind: 'brown-dwarf' };
  if (m < 8) return { mass: 0.109 * m + 0.394, kind: 'white-dwarf' };   // Kalirai et al. 2008
  if (m < 20) return { mass: 1.17 + 0.09 * m, kind: 'neutron-star' };
  if (m < 40) return { mass: 0.3 * m, kind: 'black-hole' };
  return { mass: 0.5 * m, kind: 'black-hole' };                          // direct collapse
}

/**
 * Build a fully-specified star from a mass, an age and a metallicity.
 * Post-main-sequence stars are evolved with coarse but honest scalings:
 * a red giant is cool and enormous, a white dwarf is hot and Earth-sized,
 * a neutron star is a 12 km sphere at a million kelvin.
 */
export function makeStar(massMsun: number, ageGyr: number, metallicity = 0, rng?: RNG): Star {
  const life = msLifetimeGyr(massMsun);
  let L = msLuminosity(massMsun);
  let R = msRadius(massMsun);
  let kind: StellarKind = 'main-sequence';
  let currentMass = massMsun;
  let lumClass = 'V';

  // Metallicity: metal-poor stars are hotter and slightly more luminous
  const zFac = Math.pow(10, -0.1 * metallicity);
  R *= Math.pow(10, 0.06 * metallicity);
  L *= zFac;

  if (massMsun < 0.08) {
    kind = 'brown-dwarf';
    // Brown dwarfs cool with time; crude but monotonic
    L = 1e-5 * Math.pow(massMsun / 0.08, 2.6) * Math.pow(Math.max(ageGyr, 0.01) / 5, -1.2);
    R = 0.1;
    lumClass = 'V';
  } else if (ageGyr > life) {
    const over = (ageGyr - life) / Math.max(life, 1e-4);
    if (over < 0.12) {
      // Hydrogen-shell burning: swelling and cooling
      kind = massMsun > 8 ? 'supergiant' : 'giant';
      L *= 1 + 60 * over * (massMsun > 8 ? 0.3 : 1);
      R *= 1 + 120 * over;
      lumClass = massMsun > 8 ? 'I' : 'III';
    } else {
      const rem = remnantMass(massMsun);
      kind = rem.kind;
      currentMass = rem.mass;
      if (kind === 'white-dwarf') {
        // Cooling track: Mestel's law, roughly L ∝ t^-1.3
        R = 0.0127 * Math.pow(currentMass, -1 / 3);
        const coolGyr = Math.max(ageGyr - life, 0.01);
        L = 0.1 * Math.pow(coolGyr / 0.1, -1.3);
        L = Math.max(L, 1e-6);
        lumClass = 'D';
      } else if (kind === 'neutron-star') {
        R = 12e3 / R_SUN;
        L = 1e-2 * Math.pow(Math.max(ageGyr - life, 0.001) / 0.001, -1.5);
        L = Math.max(L, 1e-8);
        lumClass = '';
      } else {
        R = (2 * 6.6743e-11 * currentMass * M_SUN) / (2.99792458e8 ** 2) / R_SUN;
        L = 0;
        lumClass = '';
      }
    }
  } else {
    // On the main sequence stars brighten slowly (the Sun is ~30% brighter than at ZAMS)
    const f = ageGyr / life;
    L *= 1 + 0.7 * f * f;
    R *= 1 + 0.2 * f;
    lumClass = 'V';
  }

  let teff: number;
  if (kind === 'black-hole') teff = 0;
  else if (kind === 'neutron-star') teff = 6e5 * Math.pow(Math.max(ageGyr - life, 1e-3) / 1e-3, -0.25);
  else teff = teffFrom(Math.max(L, 1e-12), Math.max(R, 1e-6));

  const [cls, sub] = spectralClassOf(teff);
  const color = kind === 'black-hole' ? [0.02, 0.01, 0.05] as [number, number, number] : blackbodyRGB(teff);
  const hz = habitableZone(Math.max(L, 1e-12), teff);

  void rng;
  return {
    massMsun,
    currentMassMsun: currentMass,
    luminosityLsun: L,
    radiusRsun: R,
    teff,
    ageGyr,
    lifetimeGyr: life,
    metallicity,
    kind,
    spectralClass: cls,
    subClass: sub,
    luminosityClass: lumClass,
    color,
    habitableZoneAu: hz,
  };
}

/** Human-readable spectral type, e.g. "G2 V" or "DA white dwarf". */
export function starLabel(s: Star): string {
  switch (s.kind) {
    case 'black-hole': return `${s.currentMassMsun.toFixed(1)} M☉ black hole`;
    case 'neutron-star': return `neutron star`;
    case 'white-dwarf': return `white dwarf (${s.spectralClass}${s.subClass})`;
    case 'brown-dwarf': return `${s.spectralClass}${s.subClass} brown dwarf`;
    default: return `${s.spectralClass}${s.subClass} ${s.luminosityClass}`.trim();
  }
}

/** Distance at which a star of luminosity L delivers Earth's insolation, m. */
export const insolationRadius = (Lsun: number): number => Math.sqrt(Lsun) * AU;

/** Absolute bolometric magnitude. */
export const absoluteMagnitude = (Lsun: number): number => 4.74 - 2.5 * Math.log10(Math.max(Lsun, 1e-30));

/** Apparent magnitude at a distance in parsecs. */
export const apparentMagnitude = (Lsun: number, distPc: number): number =>
  absoluteMagnitude(Lsun) + 5 * Math.log10(Math.max(distPc, 1e-9)) - 5;
